default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] || 'admin' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || '12345' %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>

development:
  <<: *default
  database: currency_tracker_development

test:
  <<: *default
  database: currency_tracker_test

production:
  <<: *default
  database: currency_tracker_production
  username: currency_tracker
  password: <%= ENV['CURRENCY_TRACKER_DATABASE_PASSWORD'] %>
